import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "@/components/NavBar";
import localFont from "next/font/local";

const suisse = localFont({
  src: "./fonnts.com-Suisse_Intl_Medium.ttf",
  display: "swap",
  variable: "--font-suisse",
});

const times = localFont({
  src: "./times.ttf",
  display: "swap",
  variable: "--font-times",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${suisse.variable} ${times.variable} antialiased`}>
        {/* <Loader /> */}
        <NavBar />
        <main>{children}</main>
      </body>
    </html>
  );
}
