// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  gallery: dynamic(() => import("./Gallery")),
  homepage: dynamic(() => import("./Homepage")),
};
